<?php

namespace ContainerMMAE6hK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I9A2Pi7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i9A2Pi7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i9A2Pi7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\article\\ArticleRepository', 'getArticleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'articleRepo' => 'App\\Repository\\article\\ArticleRepository',
            'em' => '?',
        ]);
    }
}
