<?php

namespace ContainerMMAE6hK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q1GLhcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._q1GLhc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._q1GLhc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'stock' => ['privates', '.errored..service_locator._q1GLhc.App\\Entity\\StockProduit', NULL, 'Cannot autowire service ".service_locator._q1GLhc": it needs an instance of "App\\Entity\\StockProduit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'stock' => 'App\\Entity\\StockProduit',
        ]);
    }
}
