<?php

namespace ContainerMMAE6hK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MbfkMPiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mbfkMPi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mbfkMPi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consommation' => ['privates', '.errored..service_locator.mbfkMPi.App\\Entity\\ConsommationProduit', NULL, 'Cannot autowire service ".service_locator.mbfkMPi": it needs an instance of "App\\Entity\\ConsommationProduit" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'consommation' => 'App\\Entity\\ConsommationProduit',
            'entityManager' => '?',
        ]);
    }
}
