<?php

namespace ContainerMMAE6hK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SvsQDofService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.svsQDof' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.svsQDof'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stock' => ['privates', '.errored..service_locator.svsQDof.App\\Entity\\StockProduit', NULL, 'Cannot autowire service ".service_locator.svsQDof": it needs an instance of "App\\Entity\\StockProduit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'stock' => 'App\\Entity\\StockProduit',
        ]);
    }
}
