<?php

namespace Container9sJDaEl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E72RtK7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e72RtK7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e72RtK7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.e72RtK7.App\\Entity\\article\\Article', NULL, 'Cannot autowire service ".service_locator.e72RtK7": it needs an instance of "App\\Entity\\article\\Article" but this type has been excluded in "config/services.yaml".'],
        ], [
            'article' => 'App\\Entity\\article\\Article',
        ]);
    }
}
