<?php

namespace Container9sJDaEl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T_WkdUbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T.WkdUb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T.WkdUb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'estimator' => ['privates', 'App\\Service\\article\\ImagePriceEstimatorService', 'getImagePriceEstimatorServiceService', true],
        ], [
            'estimator' => 'App\\Service\\article\\ImagePriceEstimatorService',
        ]);
    }
}
