<?php

namespace Container9sJDaEl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockProduitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._q1GLhc.App\Entity\StockProduit' shared service.
     *
     * @return \App\Entity\StockProduit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._q1GLhc": it needs an instance of "App\\Entity\\StockProduit" but this type has been excluded in "config/services.yaml".');
    }
}
