<?php

namespace ContainerGF4RxDu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtcRnGpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ptcRnGp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ptcRnGp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.OyXepzr', 'get_ServiceLocator_OyXepzrService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.xBLnkUw', 'get_ServiceLocator_XBLnkUwService', true],
            'App\\Controller\\AdminController::newUser' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\AdminController::toggleUser' => ['privates', '.service_locator.OyXepzr', 'get_ServiceLocator_OyXepzrService', true],
            'App\\Controller\\AdminController::users' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\DashboardController::admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.OyXepzr', 'get_ServiceLocator_OyXepzrService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.xBLnkUw', 'get_ServiceLocator_XBLnkUwService', true],
            'App\\Controller\\AdminController:newUser' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\AdminController:toggleUser' => ['privates', '.service_locator.OyXepzr', 'get_ServiceLocator_OyXepzrService', true],
            'App\\Controller\\AdminController:users' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\DashboardController:admin' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::newUser' => '?',
            'App\\Controller\\AdminController::toggleUser' => '?',
            'App\\Controller\\AdminController::users' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\DashboardController::admin' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:newUser' => '?',
            'App\\Controller\\AdminController:toggleUser' => '?',
            'App\\Controller\\AdminController:users' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\DashboardController:admin' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
