<?php

namespace ContainerKixopp6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M5L9AxSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m5L9AxS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m5L9AxS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'order' => ['privates', '.errored..service_locator.m5L9AxS.App\\Entity\\article\\Order', NULL, 'Cannot autowire service ".service_locator.m5L9AxS": it needs an instance of "App\\Entity\\article\\Order" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'order' => 'App\\Entity\\article\\Order',
        ]);
    }
}
