<?php

namespace ContainerKixopp6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Enxv9eqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Enxv9eq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Enxv9eq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\article\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\article\\ArticleRepository',
        ]);
    }
}
