<?php

namespace ContainerKixopp6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m5L9AxS.App\Entity\article\Order' shared service.
     *
     * @return \App\Entity\article\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m5L9AxS": it needs an instance of "App\\Entity\\article\\Order" but this type has been excluded in "config/services.yaml".');
    }
}
