<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWOrqSal\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWOrqSal/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWOrqSal.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWOrqSal\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWOrqSal\App_KernelDevDebugContainer([
    'container.build_hash' => 'WOrqSal',
    'container.build_id' => '10e7c5df',
    'container.build_time' => 1775827861,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWOrqSal');
