<?php

namespace ContainerWOrqSal;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceEstimatorControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EvmDLq6.App\Controller\article\PriceEstimatorController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EvmDLq6.App\\Controller\\article\\PriceEstimatorController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'estimator' => ['privates', 'App\\Service\\article\\ImagePriceEstimatorService', 'getImagePriceEstimatorServiceService', true],
        ], [
            'estimator' => 'App\\Service\\article\\ImagePriceEstimatorService',
        ]))->withContext('App\\Controller\\article\\PriceEstimatorController::index()', $container);
    }
}
